bundler_args: --without development
language: ruby
rvm:
  - ree
  - 1.8.6
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx
  - ruby-head
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-20mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx
    - rvm: ruby-head
  fast_finish: true
script: bundle exec rake default
